
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class screen_reward extends javax.swing.JFrame {

	/**
	 * Creates new form CLIENT_WINDOW
	 */
	public screen_reward() {
		initComponents();

		// set border to the jpanel title
		Border panel_title_border = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(235, 125, 22));
		jPanel_Title.setBorder(panel_title_border);

		// set border to the jbuttons
		Border button_border = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(255, 255, 255));

		jButton_Refresh.setBorder(button_border);

		// populate the jtable with clients data
		fillJtableWithClientsData();

	}

	public void fillJtableWithClientsData() {
		client_p client = new client_p();
		ArrayList<client_p> clientList = client.clientsList();
		String[] colNames = { "ID", "First Name", "Last Name", "Phone", "Email", "Address", "Reward" };

		Object[][] rows = new Object[clientList.size()][7];

		for (int i = 0; i < clientList.size(); i++) {
			rows[i][0] = clientList.get(i).getId();
			rows[i][1] = clientList.get(i).getFname();
			rows[i][2] = clientList.get(i).getLname();
			rows[i][3] = clientList.get(i).getPhone();
			rows[i][4] = clientList.get(i).getEmail();
			rows[i][5] = clientList.get(i).getAddress();
			rows[i][6] = clientList.get(i).getReward();
		}

		DefaultTableModel model = new DefaultTableModel(rows, colNames);
		jTable1.setModel(model);

		// change the jtable row height
		jTable1.setRowHeight(40);
		// change the jtable selection background
		jTable1.setSelectionBackground(new Color(27, 150, 77));
		// change the "ID" column width
		jTable1.getColumnModel().getColumn(0).setPreferredWidth(25);
		// change the "Address" column width
		jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel_Title = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField_Id = new javax.swing.JTextField();
		jButton_Refresh = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel8 = new javax.swing.JLabel();
		jTextField_FName = new javax.swing.JTextField();
		jButton_Refresh1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jPanel_Title.setBackground(new java.awt.Color(255, 51, 51));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("AGENTS REWARD");

		javax.swing.GroupLayout jPanel_TitleLayout = new javax.swing.GroupLayout(jPanel_Title);
		jPanel_Title.setLayout(jPanel_TitleLayout);
		jPanel_TitleLayout
				.setHorizontalGroup(jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel_TitleLayout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jLabel1).addGap(489, 489, 489)));
		jPanel_TitleLayout.setVerticalGroup(
				jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel_TitleLayout.createSequentialGroup().addContainerGap()
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
								.addContainerGap()));

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
		jLabel2.setText("ID:");

		jTextField_Id.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

		jButton_Refresh.setBackground(new java.awt.Color(51, 255, 0));
		jButton_Refresh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jButton_Refresh.setText("UPDATE");
		jButton_Refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton_Refresh.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_RefreshActionPerformed(evt);
			}
		});

		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTable1MouseClicked(evt);
			}
		});
		jScrollPane2.setViewportView(jTable1);

		jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
		jLabel8.setText("REWARD:");

		jTextField_FName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

		jButton_Refresh1.setBackground(new java.awt.Color(255, 255, 0));
		jButton_Refresh1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jButton_Refresh1.setText("Refresh");
		jButton_Refresh1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton_Refresh1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_Refresh1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addGap(39, 39, 39)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(jLabel2).addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 101,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField_FName, javax.swing.GroupLayout.PREFERRED_SIZE, 101,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 690,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(21, 21, 21))
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jButton_Refresh, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(595, 595, 595))
				.addGroup(
						jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(546, 546, 546)
										.addComponent(jButton_Refresh1, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGap(11, 11, 11))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(jPanel_Title, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(37, 37, 37)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jTextField_Id)
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
														javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(18, 18, 18)
												.addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE,
																31, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jTextField_FName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(0, 0, Short.MAX_VALUE))
										.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341,
												Short.MAX_VALUE))
								.addGap(65, 65, 65)
								.addComponent(jButton_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(33, 33, 33))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addContainerGap(502, Short.MAX_VALUE)
												.addComponent(jButton_Refresh1, javax.swing.GroupLayout.PREFERRED_SIZE,
														39, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(33, 33, 33))));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton_RefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_RefreshActionPerformed

		int id = 0;
		String rewards = null;
		try {
			id = Integer.parseInt(jTextField_Id.getText());
			rewards = (jTextField_FName.getText());

		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, "Please Enter Valid Details", "Error", 2);
		}

		PreparedStatement ps;
		PreparedStatement fs;
		ResultSet rsReward;
		ResultSet rs;
		Statement st;

		String selectquery = "update property_client set rewards=? where id=?";

		String fetchQuery = "select rewards from  property_client where id=" + id;

		try {

			st = conn.getTheConnection().createStatement();
			rsReward = st.executeQuery(fetchQuery);
			String oldReward = "";
			while (rsReward.next()) {
				oldReward = rsReward.getString(1);
			}

			if (oldReward.equalsIgnoreCase(rewards)) {
				JOptionPane.showMessageDialog(null, "No change in rewards value", "Error", 2);
			}

			else {
				ps = conn.getTheConnection().prepareStatement(selectquery);

				ps.setString(1, rewards);
				ps.setInt(2, id);

				// rs = ps.executeQuery();

				boolean success = ps.executeUpdate() > 0;

				if (success) {
					JOptionPane.showMessageDialog(null, "Reward Updated successfully", "Add Reward", 1);
					fillJtableWithClientsData();
				}
			}

		} catch (SQLException ex) {
			JOptionPane.showMessageDialog(null, "Database Error", "Error", 2);
			Logger.getLogger(login_screen.class.getName()).log(Level.SEVERE, null, ex);
		}

	}// GEN-LAST:event_jButton_RefreshActionPerformed

	private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable1MouseClicked

		int selectedRowIndex = jTable1.getSelectedRow();
		jTextField_Id.setText(jTable1.getValueAt(selectedRowIndex, 0).toString());
		jTextField_FName.setText(jTable1.getValueAt(selectedRowIndex, 6).toString());

	}// GEN-LAST:event_jTable1MouseClicked

	private void jButton_Refresh1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_Refresh1ActionPerformed
		// TODO add your handling code here:
		fillJtableWithClientsData();
	}// GEN-LAST:event_jButton_Refresh1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(screen_client.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(screen_client.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(screen_client.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(screen_client.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new screen_client().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton_Refresh;
	private javax.swing.JButton jButton_Refresh1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel_Title;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField_FName;
	private javax.swing.JTextField jTextField_Id;
	// End of variables declaration//GEN-END:variables
}
